- config.nims
This PR adds a `config.nims` that provides:
- A few compiler defaults (some of them based on PR #20) .
- A Nim task `test` to run all the units in the repo as executables, with an assumption it runs tests. Task runs with `nim test`.
This task is a proposed replacement for the shell scripts from PR #20.
Main benefits over Bash: cross-platform, no additional dependencies.
- A Nim task `prettyfy` ro run `nimpretty` on all *.nim files in the repository. Task runs with `nim prettyfy`
This task is a proposed replacement for the shell script from PR #19.
List of compiler defaults:
```nim
--gc:arc
--checks:on
--assertions:on
--spellSuggest
--styleCheck:error
```
> chore: add `config.nims` with nim defaults & chore tasks

- searches/binary_search.nim
I used linear_search.nim as base, so `checkBinarySearch` template is redundant, but could be useful in future for other implementations. I am also not sure if it is a good idea or not to check if array is sorted at the start of function; for example:
```
from std/algorithm import isSorted, SortOrder
func binarySearch*[T:Ordinal](arr: openArray[T], key: T): Option[Natural] {.raises: [ValueError].} =
if not arr.isSorted(Ascending):
raise newException(ValueError, "Array is not sorted or not in ascending order.")
```
> Add binary search

- maths/arc_length.nim
Compute arc length on a circle for both degrees and radians input. Generic curves would require integration algorithms.
Based on [Python's implementation](https://the-algorithms.com/algorithm/arc-length)
> Add arc length (circle)

- searches/linear_search.nim
Fix #31 and CI. Ran nimpretty directly.
> Fix linear search

- .gitpod.dockerfile
Things added/changed:
- Run `sudo apt-get update` before running other commands on the Gitpod Dockerfile.
> chore: run `apt-get update` before running other commands

- README.md
* Fixes the gitter badge link
* Added Matrix badge and links
* Use more extended markdown syntax instead of HTML in header
This PR supersedes PR #40 by @dlesnoff, sorry for this. 
I tried to suggest a quick fix there and broke the formatting, and couldn't suggest additional fixes that include the starting lines that were not touched by the original commit there, so an alternative PR seemed like the easiest way to quickly fix everything.
Fixes #39.
> Readme: fix gitter link, add Nim logo, formatting fixes

- maths/arc_length.nim
Removed some dangling whitespace.
> chore: fix CI with nimpretty for `arc_length.nim`

- config.nims
- nim.cfg
Fixes #26 and removes the now unused `nim.cfg`
Setting the `mm`/`gc` switch turned out to be position-sensitive. Moving it below the imports helps. Will not be necessary as soon as the fixes from devel land in the stable compiler branch. The switch is renamed to the not deprecated `mm` version.
This also silences the `BareExcept` warning when running tests with `nim test` that mostly stem from the `std/unittest`. The used compiler switch (`warning[BareExcept]:off`) surprisingly works fine on stable but didn't work reliably on devel (should be fixed with nim-lang/Nim/pull/21390 by now).
> chore: `gc`->`mm`, move back to `config.nims`, fixes #26

- DIRECTORY.md
- dynamic_programming/catalan_numbers.nim
- dynamic_programming/viterbi.nim
- maths/arc_length.nim
This PR adds a missing `#` in the `module-level documentation` in changed `*.nim` files. It not only adapts these files to the [contributing guidelines](https://github.com/vil02/Nim/blob/17c4c39a31e2e0e56110d9117ba2c5d4d8916e20/CONTRIBUTING.md) but also removes the warnings when executing `nim r .scripts/directory.nim`.
> docs: add missing `#`

- stable_marriage/gale_shapley.nim
This is an adaptation of my much [earlier implementation](https://rosettacode.org/wiki/Stable_marriage_problem#Nim) made for the RosettaCode project. The additional requirements of the task were moved to the runnableExamples block.
The code was updated, thoroughly checked and commented.
The name for the category is similar to one used for earlier [C#](https://github.com/TheAlgorithms/C-Sharp/tree/master/Algorithms/Problems/StableMarriage) and [Lua](https://github.com/TheAlgorithms/Lua/tree/main/src/misc/stable_marriage) implementations.
> Implement Gale-Shapley stable matching

- .github/workflows/nim_test.yml
- config.nims
Since [Nim 1.6.14 was released](https://nim-lang.org/blog/2023/06/27/version-1614-released.html) I suggest to use it in [nim_test.yml](https://github.com/TheAlgorithms/Nim/blob/510b70c01dc3f2f653bcbaf00896d7ea1c8db6f2/.github/workflows/nim_test.yml).
Regarding
https://github.com/TheAlgorithms/Nim/blob/510b70c01dc3f2f653bcbaf00896d7ea1c8db6f2/config.nims#L16
when I move this _above the imports_ I get:
```
/home/userName/.choosenim/toolchains/nim-1.6.14/lib/pure/parseutils.nim(426, 21) Error: system module needs: nimDestroyAndDispose
```
> chore: use nim 1.6.14

- dynamic_programming/catalan_numbers.nim
Since `devel` has become `1.9.5`, the [`nim_test_cyclic`](https://github.com/TheAlgorithms/Nim/blob/231960bd4d8d96a020ce34c82f066edb61510fbf/.github/workflows/nim_test_cyclic.yml) is failing, with the error (cf. [log](https://github.com/TheAlgorithms/Nim/actions/runs/5709792795/job/15469089378)):
```
Testing dynamic_programming/catalan_numbers.nim:
/home/runner/work/Nim/Nim/dynamic_programming/catalan_numbers.nim(24, 5) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
/home/runner/work/Nim/Nim/dynamic_programming/catalan_numbers.nim(18, 3) Error: 'result' requires explicit initialization
```
This `PR` fixes this issue ~~with an aid of [`std/sequtils`](https://nim-lang.org/docs/sequtils.html) (cf. …
> fix: resolve `ProveInit` error in `catalanNumbersRecursive`

- .github/workflows/nim_test.yml
- config.nims
As mentioned in #55, it is possible to use the nim version 2.0.0 in [`nim_test`](https://github.com/TheAlgorithms/Nim/blob/9f045f79cd4a81fc08efe67f04158d92712f08e1/.github/workflows/nim_test.yml) workflow (cf. [Nim v2.0 released](https://nim-lang.org/blog/2023/08/01/nim-v20-released.html)).
When nim version is updated, it is also possible to _move_ `--mm:arc` _above_ imports in https://github.com/TheAlgorithms/Nim/blob/9f045f79cd4a81fc08efe67f04158d92712f08e1/config.nims#L16
> chore: use nim 2.0.0

- .gitpod.dockerfile
This PR simplifies the `.gitpod.dockerfile` by using `$HOME` for _constructing_ the path, where `nim` is.
> style: use `$HOME` in nim path

- .github/workflows/check_code_format.yml
- .github/workflows/nim_test.yml
- .github/workflows/nim_test_cyclic.yml
The `actions/checkout@v4` was recently [released](https://github.com/actions/checkout/releases/tag/v4.0.0).
> chore: update `actions/checkout` to `v4`

- config.nims
As pointed out by @ZoomRmc in https://github.com/TheAlgorithms/Nim/pull/62#pullrequestreview-1737253041 this projects uses uses 2-space indentation. However, the [current](https://github.com/TheAlgorithms/Nim/blob/ac2b056645f550994a9ca9e67038f55d4fe262ba/config.nims#L51) setup accepts files with 4-space indentation. This PR is an attempt to fix that.
> chore: run `nimpretty` with `--indent:2`

- dynamic_programming/catalan_numbers.nim
[`std/sequtils`](https://github.com/TheAlgorithms/Nim/blob/ac2b056645f550994a9ca9e67038f55d4fe262ba/dynamic_programming/catalan_numbers.nim#L15) are [unused](https://github.com/TheAlgorithms/Nim/actions/runs/6765358794/job/18384910968#step:5:44). This PR fixes that.
> style: remove unused import in `catalan_numbers.nim`

- .github/workflows/nim_test.yml
[Nim 2.0.2](https://nim-lang.org/blog/2023/12/19/versions-1618-202-released.html) was released. This PR makes a suitable update.
> chore: use nim version `2.0.2`

- .github/workflows/nim_test.yml
[Nim 2.0.4](https://nim-lang.org/blog/2024/04/16/versions-1620-204-released.html) and [Nim 2.0.8](https://nim-lang.org/blog/2024/07/03/version-208-released.html) was relleased. This PR makes a suitable update.
Similar to #67.
> chore: use nim version `2.0.8`

- .github/workflows/check_code_format.yml
- .gitignore
The directory `.nim_runtime` created by the new version of the github action `setup-nim-action` must be escaped by all commands including nim prettyfy.
I can not merge this PR myself, so please have a look at it @Panquesito7  as soon as it is validated by e.g. @vil02
> Fix check code format wf

- maths/haversine_distance.nim
This PR adds a `haversineDistance` function.
I realize that the `close` function is _ugly_. I could not force the [`almostEqual`](https://nim-lang.org/docs/math.html#almostEqual%2CT%2CT%2CNatural) to work here.
> feat: add `haversineDistance`

- .github/workflows/build_directory_md.yml
Fixes the `build_directory_md.yml` action. ~~Sets the Nim runtime dir as a forced git exclusion~~.
`git clean` removed the nim compiler directory, which `jiro4989/setup-nim-action@v2` installs to `$(pwd)/.nim_runtime`.
This puts the nim install dir outside of the current project directory with:
```yml
- uses: jiro4989/setup-nim-action@v2
with:
parent-nim-install-directory: ${{ runner.temp }}
```
> Chore: fix build_directory_md.yml

- maths/modular_inverse.nim
- strings/check_anagram.nim
- **Specify template's return type for correct variable declaration**
I specified the return type of a template in strings/check_anagram.nim
There was an error about non-discarded char elements, as somehow these values were not considered part of the declaration.
I am not super fan of this fix, as one branch of the case switch just errors out and do not return a value. I am all ears for a better fix.
- **[modular_inverse] Reduce the number of tests to make CI readable again**
The CI was not very readable due to a too great number of tests in the maths/modular_inverse.nim file. I reduced the number of tests from 1000 to 10.
> Fix and clean CI after Nim 2.2.0 update

- .github/workflows/nim_test.yml
- maths/modular_inverse.nim
[Nim 2.2.0](https://nim-lang.org/blog/2024/10/02/nim-220-2010.html) was released.
[Nim 2.2.2](https://nim-lang.org/blog/2025/02/05/nim-222.html) was released too.
Similar to #73. Possible due to #84.
> chore: use nim version `2.2.2`
